### ISSUE TITLE
Clarification: does it support stacked notifications?

### ISSUE THREAD

**Issue by BrainCrumbz** [zachatrocity/netoaster#4]
Hello there

thanks for sharing your work in the open. 

Me and my team could not figure out the following: does this library allow for showing notification stacked (for example) one on top of the other, when they are produced faster than they fade? Something similar to how [this other library](https://github.com/raflop/ToastNotifications) behaves.

Thanks

**Comment by zachatrocity** [comment]
Not currently no. Sadly I've lost my visual studio license since I graduated so I've been unable to do work on this library. I'm active on github though so I'm still open to pull requests!

**Comment by BrainCrumbz** [comment]
Just in case, have you tried working with VS Community edition? That is free and it let you go quite far in development...

**Comment by zachatrocity** [comment]
Hmm No I haven't, I thought it was strictly web development. Looks like it'll work for what I need. I'll download it and update this library.

**Comment by BrainCrumbz** [comment]
Yep, it totally works for WPF apps, ASP.NET / Core web, and of course all the rest (ClassLib, Console, ...). You miss a number of advanced features like load/stress test, but it can go a long way. Good!

**Comment by zachatrocity** [comment]
Cool stuff, I'll close this issue once I've implemented stacked notifications.

**Comment by BrainCrumbz** [comment]
If you feel like, you could share ideas on how to design & develop the stacking feature. Maybe our team can lend a hand if we manage to get into source code & have an understanding about it. Just our 2c!

**Comment by zachatrocity** [comment]
That would be great. I haven't been able to put to much time into this other than creating the feature branch.

I was thinking I would add a Guid and DateTime to each toast. In the ToastSupport.cs I would have an Array/List of toasts and add to it every time a toast is fired. Then likely in the [GetAnimation](https://github.com/zachatrocity/netoaster/blob/master/netoaster/ToastSupport.cs#L42) function I would check the Array/List and update the new animation position based on the amount of toasts in the array. 

This could probably be implemented in a better way so if you or one of your team has an idea tell them to run with it!

**Comment by BrainCrumbz** [comment]
Hi there. Just to not leave this totally hanging: 

we just noticed that preferred approach in using this library is through code-behind. We're actually going for a stronger MVVM approach, actually a _view-model first_ one, with Caliburn.Micro so that type of usage does not seem to fit for us. That's why I'm not sure we can take advantage of this library.

**Comment by zachatrocity** [comment]
Okay sounds good. I made this Library for a very specific project I was working on in my company and it break MVVM. No worries.
