### ISSUE TITLE
Bug: demoapp not in sync with v1.0.7

### ISSUE THREAD

**Issue by BrainCrumbz** [zachatrocity/netoaster#6]
Hi there

in order to try the library, we just downloaded a ZIP copy of project, and in particular of the [toasterdemoapp](https://github.com/zachatrocity/netoaster/tree/4c27e33115f164b6de9f309f4113ad144d1d3485/toasterdemoapp). Then we removed original project reference to netoaster source code and installed the package instead from nuget (v1.0.7, latest available).

At this point we found issues with the API used from demo app: 
- `Toast()` method in `ErrorToaster`, `SuccessToaster`, `WarningToaster` all use 6 parameters, while now library requires at most 4:

``` c#
xxx.Toast(
  this, 
  TitleText.Text, 
  MessageText.Text, 
  position: (ToasterPosition)selectbox.SelectedItem, 
  animation: (ToasterAnimation)aniselectbox.SelectedItem, 
  margin: 20.0);
```

I guess the first two parameters should be dropped, so e.g. the title is gone.
- `InfoToaster` cannot be found anymore.

**Comment by zachatrocity** [comment]
Yes it appears the demo app needs to be updated to use the nuget package and latest API.

**Comment by zachatrocity** [comment]
This is fixed. Updated package to 1.0.8 and made the demo app use a nuget reference.
